parameters:
  ResourceId:
    in: path
    name: id
    required: true
    type: integer
    description: 'The resource ID'

  ResourceUuid:
    in: path
    name: id
    required: true
    type: string
    format: uuid
    description: 'The resource UUID'

  Action:
    name: action
    in: query
    type: string
    required: true
    description: 'Action parameter for non-CRUD actions'
